--**Numpy**--

In [1]:
import numpy as np

In [2]:
x = np.arange(14)
y = np.arange(31)

In [3]:
x
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
print(x)
y

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [6]:
a = np.arange(16).reshape(4,4)

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(4, 4)
16
int64
8
<class 'numpy.ndarray'>


In [10]:
z = np.array( [1.0, 2.0, 3.0, 4.0] )
print(z)
print(z.dtype)
print(type(z))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [11]:
abc = np.eye(5)
dtype=np.float64
abc

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
d = np.linspace(-1, 3, 20, endpoint=True)
print(d)

[-1.         -0.78947368 -0.57894737 -0.36842105 -0.15789474  0.05263158
  0.26315789  0.47368421  0.68421053  0.89473684  1.10526316  1.31578947
  1.52631579  1.73684211  1.94736842  2.15789474  2.36842105  2.57894737
  2.78947368  3.        ]


In [13]:
d = np.linspace(-1, 3, 20, endpoint=False)
print(d)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6
  1.8  2.   2.2  2.4  2.6  2.8]


In [14]:
e = np.logspace(-1, 3, 20, endpoint=True, base=10)
print(e)

[1.00000000e-01 1.62377674e-01 2.63665090e-01 4.28133240e-01
 6.95192796e-01 1.12883789e+00 1.83298071e+00 2.97635144e+00
 4.83293024e+00 7.84759970e+00 1.27427499e+01 2.06913808e+01
 3.35981829e+01 5.45559478e+01 8.85866790e+01 1.43844989e+02
 2.33572147e+02 3.79269019e+02 6.15848211e+02 1.00000000e+03]


In [15]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [16]:
f = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [17]:
f = np.fromfunction(lambda i, j: i != j, (5, 5), dtype=int)
f

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

--**Array Operations**--

In [21]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
a*4

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76]])

In [23]:
a + a*2

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [24]:
a*a

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [25]:
b = a.transpose()
b

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [26]:
a @ b

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [27]:
print(a)
a.sum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([10, 35, 60, 85])

In [28]:
print(a)
a.sum(axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([30, 34, 38, 42, 46])

In [29]:
a.sum()

190

In [30]:
print(a.min(), a.max())

0 19


--**Universal Functions**--

In [32]:
b = a*np.pi/5.0
print(b)

[[ 0.          0.62831853  1.25663706  1.88495559  2.51327412]
 [ 3.14159265  3.76991118  4.39822972  5.02654825  5.65486678]
 [ 6.28318531  6.91150384  7.53982237  8.1681409   8.79645943]
 [ 9.42477796 10.05309649 10.68141502 11.30973355 11.93805208]]


In [33]:
c = np.cos(b)
print(c)

[[ 1.          0.80901699  0.30901699 -0.30901699 -0.80901699]
 [-1.         -0.80901699 -0.30901699  0.30901699  0.80901699]
 [ 1.          0.80901699  0.30901699 -0.30901699 -0.80901699]
 [-1.         -0.80901699 -0.30901699  0.30901699  0.80901699]]


In [34]:
d = b + c 

In [35]:
print(d)

[[ 1.          1.43733553  1.56565406  1.5759386   1.70425713]
 [ 2.14159265  2.96089419  4.08921272  5.33556524  6.46388377]
 [ 7.28318531  7.72052083  7.84883936  7.8591239   7.98744244]
 [ 8.42477796  9.2440795  10.37239803 11.61875055 12.74706908]]


In [36]:
d

array([[ 1.        ,  1.43733553,  1.56565406,  1.5759386 ,  1.70425713],
       [ 2.14159265,  2.96089419,  4.08921272,  5.33556524,  6.46388377],
       [ 7.28318531,  7.72052083,  7.84883936,  7.8591239 ,  7.98744244],
       [ 8.42477796,  9.2440795 , 10.37239803, 11.61875055, 12.74706908]])

In [37]:
a = np.arange(14)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [38]:
a[7]

7

In [39]:
print(a[4:9])

[4 5 6 7 8]


In [40]:
a[6:8]

array([6, 7])

In [41]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [42]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
a[1,2]

5

In [45]:
a[1:2,1:2]

array([[4]])

In [46]:
a[:,1]

array([1, 4, 7])

In [47]:
a = a.flatten()
print(a)

[0 1 2 3 4 5 6 7 8]


In [48]:
for j in a:
    print(j)
a = np.arange(9).reshape(3,3)
print(a)

0
1
2
3
4
5
6
7
8
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8


In [50]:
a = np.arange(18)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [51]:
b = a
b is a

True

In [54]:
b.shape = (3, 6)
print(b)
a.shape

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


(3, 6)

In [55]:
b is a

True

In [56]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [57]:
a = np.arange(30)
c = a[:]
a.shape = (5,6)

print(a)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [58]:
c[8] = -00
print(a)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  0  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  0  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [59]:
d = c[9:22]
print(d)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21]


In [60]:
d[:] = 0 

In [61]:
print(a)
print(c)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 22 23]
 [24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0 22 23
 24 25 26 27 28 29]
[0 0 0 0 0 0 0 0 0 0 0 0 0]


In [62]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [63]:
d = a.copy()
d[:,:] = 3.3
print(a)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 22 23]
 [24 25 26 27 28 29]]
[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


--**Boolean Indexing**--

In [65]:
a = np.arange(21).reshape(3,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [66]:
a[a > 9] = 0
a

array([[0, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [67]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]])

In [68]:
a[a != 0] = -1
a

array([[-1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]])

In [69]:
a == -1

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [71]:
a = np.arange(15).reshape(3,5)
a[np.logical_and(a > 4, a <= 9)] = 0.0
a

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14]])

In [72]:
a > 4

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [73]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=False)

print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [74]:
import time
import numpy as np
M = 16
N = 32

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)


In [75]:
t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0015892982482910156 s


In [76]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.     0.0625 0.125  0.1875 0.25   0.3125 0.375  0.4375 0.5    0.5625
 0.625  0.6875 0.75   0.8125 0.875  0.9375]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]


In [77]:
t0 = time.time()
g2 = np.sin(3.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.00036787986755371094 s


--**Concatenation of arrays**--

In [78]:
x = np.array([11, 22, 33, 44])
y = np.array([44, 33, 22, 11])
np.concatenate([y,x])

array([44, 33, 22, 11, 11, 22, 33, 44])

In [79]:
x = np.array([11, 22, 33, 44])
y = np.array([44, 33, 22, 11])
np.concatenate([x,y])

array([11, 22, 33, 44, 44, 33, 22, 11])

In [82]:
z = [55, 66, 77]
print(np.concatenate([y, x, z]))

[44 33 22 11 11 22 33 44 55 66 77]


In [83]:
grid = np.array([[10, 20, 30],
                 [40, 50, 60]])

In [84]:
np.concatenate([grid, grid])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [85]:
np.concatenate([grid, grid], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [86]:
np.concatenate([grid, grid], axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

--**Splitting of arrays**--

In [89]:
x = [44, 33, 22, 11, 11, 22, 33, 44, 55, 66, 77]
x1, x2, x3,x4 = np.split(x, [3, 5,8])
print(x1, x2, x3, x4)

[44 33 22] [11 11] [22 33 44] [55 66 77]


In [90]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
left, right = np.hsplit(grid, [4])
print(left)
print(right)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


--**Aggregates**--

In [92]:
x = np.arange(1, 14)
print(x)
np.add.reduce(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


91

In [93]:
np.multiply.reduce(x)

6227020800

In [94]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91])

In [95]:
np.multiply.accumulate(x)

array([         1,          2,          6,         24,        120,
              720,       5040,      40320,     362880,    3628800,
         39916800,  479001600, 6227020800])